export {Typography} from 'UI/Typography/Typography.jsx'
export {CustomButton} from './Buttons/CustomButton/CustomButton.jsx'
export {Heading} from 'UI/Heading/Heading.jsx'
export {FollowUs} from './FollowUs/FollowUs.jsx'
export {WeInNumber} from './WeInNumber/WeInNumber.jsx'
export {YoutubeBlock} from './YoutubeBlock/YoutubeBlock.jsx'
export {Container} from './Container/Container.jsx'
export {Card} from './Card/Card.jsx'